"infinitive","participle_I","participle_II","translation"
"abbringen von","","","apartar de"
"abdichten gegen","","","aislar contra"
"abhängen von","","","depender de"
"abhärten gegen","","","fortalecerse contra"
"ablassen von","","","desistir de"
"ableiten aus","","","derivarse de"
"abnehmen","abnehmend","abgenommen","quitar"
"abschirmen gegen","","","proteger contra"
"abschreiben von","","","copiar de"
"absetzen auf","","","depositar en"
"abstellen für","","","enviar a"
"abtrocknen","abtrocknend","abgetrocknet","secar"
"abweichen von","","","desviarse de"
"achten auf","","","cuidar de"
"achtgeben auf","","","atender a"
"adaptieren für","","","adaptar a"
"agitieren für","","","hacer propaganda por"
"agitieren gegen","","","hacer propaganda contra"
"anbieten","anbietend","angeboten","ofrecer"
"annehmen","annehmend","angenommen","aceptar, tomar"
"anrufen","anrufend","angerufen","llamar"
"anschauen","anschauend","angeschaut","mirar"
"anstoßen auf","","","brindar por"
"anstrengen","anstrengend","angestrengt","cansar"
"antworten auf","antwortend","geantwortet","responder a, contestar a"
"anzünden","anzündend","angezündet","encender fuego"
"arbeiten","arbeitend","gearbeitet","trabajar"
"aufgeben","aufgebend","aufgegebenn","rendirse, dejar"
"aufheben","aufhebend","aufgehoben","recoger"
"aufmachen","aufmachend","aufgemacht","abrir"
"aufnehmen","aufnehmend","aufgenommen","asimilar"
"aufräumen","aufräumend","aufgeräumt","ordenar"
"aufstehen","","","levantarse, ponerse de pie"
"aufwachen","","","dejar de dormir"
"aufwecken","","","despertar"
"aufwärmen","","","recalentar"
"ausfallen","ausfallend","ausgefallen","llamar la atención"
"ausgeben","ausgebend","ausgegeben","distribuir, emitir, dar"
"ausgeben","ausgebend","ausgegeben","gastar, dar"
"auspacken","auspackend","ausgepackt","desempaquetar"
"ausrüsten mit","","","equipar con"
"ausschalten","ausschaltend","ausgeschaltet","apagar"
"ausschlafen","","","dormir a gusto"
"aussprechen","aussprechend","ausgesprochen","expresar"
"aussuchen","aussuchend","ausgesucht","elegir"
"ausweichen","ausweichend","ausgewichen","evitar"
"ausweisen auf","","","expulsar de"
"auswählen aus","","","escoger de"
"ausziehen","ausziehend","ausgezogen","quitarse"
"backen","backend","gebacken","cocinar, hornear"
"baden","badend","gebadet","bañarse"
"bauen","bauend","gebaut","construir"
"beachten","beachtend","beachtet","cumplir con"
"beantragen","beantragend","beantragt","solicitar"
"beantworten","beantwortend","beantwortet","contestar"
"bedienen","bedienend","bedient","atender"
"befinden","","befunden","encontrarse"
"begegnen","begegnend","begegnet","encontrarse"
"beginnen bei","","","empezar por"
"beginnen mit","","","empezar con"
"beginnen","beginnend","begonnen","comenzar"
"begründen","begründend","begründet","fundamentar"
"begrüssen","begrüssend","begrüsst","saludar"
"behalten","behaltend","behalten","conservar"
"bekleiden","","","vestir"
"bekommen","bekommend","bekommen","obtener"
"bemerken","bemerkend","bemerkt","darse cuenta"
"benachrichtigen","benachrichtigend","benachrichtigt","informar"
"benutzen","benutzend","benutzt","usar"
"beraten","beratend","beraten","aconsejar"
"bergen","bergend","geborgen","rescatar"
"beruhigen","beruhigend","beruhigt","tranquilizar"
"berücksichtigen","berücksichtigend","berücksichtigt","tener en cuenta"
"beschreiben","beschreibend","beschrieben","describir"
"besichtigen","besichtigend","besichtigt","visitar, examinar"
"besitzen","besitzend","besessen","poseer"
"bestehen aus","","","consistir en, componerse de"
"beweisen","","bewiesen","probar"
"bitten um","","","pedir"
"bleiben bei","","","mantenerse en, reafirmarse en"
"bürgen für","","","avalar a"
"denken","denkend","gedacht","pensar"
"einbauen in","","","insertar en"
"einbinden in","","","incluir en"
"eindecken mit","","","abastecerse de"
"einschlafen","","","qudarse dormir"
"einstehen für","","","responder por"
"entbinden von","","","eximir de"
"entscheiden","","","decidir, resolver"
"entschlafen","","","fallecer"
"entschuldigen bei","","","disculparse ante"
"entschuldigen für","","","disculparse por"
"entspringen","entspringend","entsprungen","resultar de"
"ermitteln","","","determinar, calcular"
"erwachsen","erwachsend","erwachsen","crecer"
"essen","essend","gegessen","comer"
"frühstücken","","","desayunar"
"geld ausgeben für","ausgebend","ausgegeben","gastar dinero para"
"grillen","grillend","gegrillt","asar"
"hantieren mit","","","ocuparse de"
"helfen bei","","","ayudar en"
"hinzufügen zu","","","annadir, agregar"
"ignorieren","","","ignorar"
"impfen","impfend","geimpft","vacunar"
"interessieren für","","","interesarse por"
"kleiden","","","vestir"
"kochen","kochend","gekocht","cocinar"
"kommen aus","","","venir de"
"kümmern um","","","atender a, cuidar de"
"laufen","laufend","gelaufen","correr"
"machen","machend","gemacht","hacer"
"multiplizieren mit","","","multiplicar por"
"nachdenken über","","","reflexionar sobre"
"nachfragen bei","","","consultar a"
"nehmen","nehmend","genommen","tomar, apoderarse"
"protestieren gegen","","","protestar contra"
"protzen mit","","","hacer gala de"
"rechnen mit","","","contar con"
"reden mit","","","hablar con"
"reden über","","","hablar sobre"
"schlafen","","","dormir"
"schlafen","schlafend","geschlafen","dormir"
"sehen","sehend","gesehen","ver"
"sein","seiend","gewesen","ser, estar"
"sich entscheiden für","","","decidirse por"
"sich freuen auf","","","alegrarse de"
"sich kleiden","","","vestirse"
"sich treffen mit","","","quedar con"
"sich umziehen","","","cambiarse/mudarse (de ropa)"
"sich verhalten","","","comportarse, portarse"
"sich verlieben in","","","enamorarse de"
"singen","singend","gesungen","cantar"
"sorgen für","","","ocuparse de"
"spielen","spielend","gespielt","jugar"
"sprechen mit","","","hablar con"
"sprechen","sprechend","gesprochen","hablar"
"suchen","suchend","gesucht","buscar"
"teilen mit","","","compartir con"
"teilen","teilend","geteilt","partir, dividir"
"tragen","","","vestir, llevar, sostener"
"trinken","trinkend","getrunken","beber"
"tun","tuend","getan","hacer"
"umziehen nach","","","mudarse a"
"vermuten","","","suponer, presumir, esperar"
"vernetzen","","","unir, conectar"
"versunken in","","","abstraído en"
"vertauschen für","","","cambiar por"
"vertreiben aus","","","expulsar de"
"wandeln","","","cambiar, convertir"
"warten auf","","","esperar a"
"wecken","","","despetar"
"werden","werdend","geworden","aux.,transformarse"
"zerstreiten wegen","","","pelearse por"
"zerteilen in","","","dividir en"
"zielen auf","","","referirse a"
"zurücktreten von","","","renunciar a"
"zusammenhängen mit","","","estar relacionado con"
"zuschießen auf","","","abalanzarse sobre"
